services:
  database:
    image: postgres
    container_name: onlinebalance_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty12345
      - POSTGRES_DB=onlinebalance_db
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - onlinebalance_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  backend:
    develop:
      watch:
        - action: rebuild
          path: .
    ports:
        - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onlinebalance_web
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=onlinebalance_db;User Id=postgres;Password=qwerty12345;
    depends_on:
      database:
        condition: service_healthy
    networks:
      - onlinebalance_network

volumes:
  postgres_data:

networks:
  onlinebalance_network:
    driver: bridge